name: iotawatt-postgrest

services:
  timescale:
    image: timescale/timescaledb:latest-pg17
    container_name: timescale
    env_file:
      - .env
    volumes:
      - timescale-pgdata:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/00_init_db.sh:ro
    ports:
      # outside:inside
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 500ms
      timeout: 500ms
      retries: 5
      start_period: 2s

  postgrest:
    image: postgrest/postgrest:latest
    container_name: postgrest
    depends_on:
      timescale:
        condition: service_healthy
    env_file:
      - .env
    ports:
      # outside:inside
      - "${POSTGREST_EXTERNAL_PORT}:3000"
    environment:
      PGRST_DB_URI: postgres://${PGRST_DB_USER}:${PGRST_DB_PASSWORD}@timescale:5432/${POSTGRES_DB}
      PGRST_LOG_LEVEL: info
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 500ms
      timeout: 500ms
      retries: 5
      start_period: 2s
volumes:
  timescale-pgdata:
    name: timescale-pgdata
