services:
  db:
    image: timescale/timescaledb:2.16.1-pg16
    container_name: timescale-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      # Pass authenticator password to init scripts
      PGRST_DB_PASSWORD: ${PGRST_DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/00_init_db.sh:ro
    ports:
      # outside:inside
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 500ms
      timeout: 500ms
      retries: 5
      start_period: 2s

  postgrest:
    image: postgrest/postgrest:v12.0.2
    container_name: postgrest-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      # outside:inside
      - "${POSTGREST_EXTERNAL_PORT}:3000"
    environment:
      PGRST_DB_URI: postgres://${PGRST_DB_USER}:${PGRST_DB_PASSWORD}@db:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_ROLE_CLAIM_KEY: ${PGRST_ROLE_CLAIM_KEY}
      PGRST_LOG_LEVEL: info
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 500ms
      timeout: 500ms
      retries: 5
      start_period: 2s
volumes:
  pg_data:
